backend:
  name: git-gateway
  branch: main

media_folder: "article-banners"
public_folder: "/article-banners"

publish_mode: editorial_workflow

theme:
  include_built_in_themes: false
  default_theme: The Silicon Dark
  themes:
    - name: The Silicon Dark
      text:
        primary: "#ffffff"         # Main text is white
        secondary: "#b3d3f7"       # Subtle text, matches light blue accent
        disabled: "#6c7a89"
      background:
        main: "#181c23"            # Main background (dark)
        light: "#232837"           # Slightly lighter for cards/inputs
        dark: "#10131a"            # Even darker for sidebar
        divider: "#232837"
      scrollbar:
        main: "#69a4ed"
        light: "#232837"
      button:
        disabled: "#232837"
      primary:
        main: "#69a4ed"            # Light blue for accents, buttons, links, headings
        light: "#b3d3f7"
        dark: "#3776b6"
        contrastColor: "#181c23"
      error:
        main: "#e74c3c"
        light: "#ffb3b3"
        dark: "#c0392b"
        contrastColor: "#ffffff"
      warning:
        main: "#ffb347"
        light: "#ffe0b3"
        dark: "#b6842c"
        contrastColor: "#181c23"
      info:
        main: "#69a4ed"
        light: "#b3d3f7"
        dark: "#3776b6"
        contrastColor: "#181c23"
      success:
        main: "#27ae60"
        light: "#81c784"
        dark: "#219150"
        contrastColor: "#181c23"
      codemirror:
        theme: dark

      typography:
        fontFamily: "'JetBrains Mono', 'Kalam', monospace, sans-serif"
        headings:
          fontFamily: "'Kalam', cursive, 'JetBrains Mono', monospace, sans-serif"
          color: "#69a4ed"        # Headings/titles in light blue
        fontSize: 16

collections:
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "article" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "banner", label: "Banner", widget: "image" }
      - { name: "description", label: "Description", widget: "string", required: false }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }