backend:
  name: git-gateway
  branch: main

logo_url: /images/logo.png

media_folder: "article-banners"
public_folder: "/article-banners"

theme:
  include_built_in_themes: false
  default_theme: The Silicon Dark
  themes:
    - name: The Silicon Dark
      common:
        gray: "#232837"
      text:
        primary: "#ffffff"
        secondary: "#b3d3f7"
        disabled: "#6c7a89"
      background:
        main: "#181c23"
        light: "#232837"
        dark: "#10131a"
        divider: "#232837"
      scrollbar:
        main: "#69a4ed"
        light: "#232837"
      button:
        disabled: "#232837"
      primary:
        main: "#69a4ed"
        light: "#b3d3f7"
        dark: "#3776b6"
        contrastColor: "#181c23"
      error:
        main: "#e74c3c"
        light: "#ffb3b3"
        dark: "#c0392b"
        contrastColor: "#ffffff"
      warning:
        main: "#ffb347"
        light: "#ffe0b3"
        dark: "#b6842c"
        contrastColor: "#181c23"
      info:
        main: "#69a4ed"
        light: "#b3d3f7"
        dark: "#3776b6"
        contrastColor: "#181c23"
      success:
        main: "#27ae60"
        light: "#81c784"
        dark: "#219150"
        contrastColor: "#181c23"
      codemirror:
        theme: dark

collections:
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    slug: "{{fields.title}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "article" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "banner", label: "Banner", widget: "image" }
      - { name: "description", label: "Description", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }